### ISSUE TITLE
Demo is not working

### ISSUE THREAD

**Issue by d9k** [RickCarlino/KoalaSRS#54]
Gray page at https://koala.vaporsoft.xyz/user, console errors:

```
{name: 'Internal Server Error.', message: '500 - Internal Server Error.', statusCode: 500}

_app-a076690c1f35306d.js:4 A client-side exception has occurred, see here for more info: https://nextjs.org/docs/messages/client-side-exception-occurred

_app-a076690c1f35306d.js:4 
        
        
POST https://koala.vaporsoft.xyz/api/trpc/getUserSettings?batch=1 401 (Unauthorized)

_app-a076690c1f35306d.js:4 Failed to fetch user settings: TRPCClientError: Please log in.
    at l.from (_app-a076690c1f35306d.js:4:20349)
    at _app-a076690c1f35306d.js:4:25032
```

**Comment by RickCarlino** [comment]
Hi @d9k , thanks for letting me know about the problem.

You are the first person to raise an issue on this repo, so congratulations on that :sweat_smile: 

I will investigate the problem. For now, you can sign in via https://koala.vaporsoft.xyz/api/auth/signin

**Comment by RickCarlino** [comment]
I have a fix available here, but I can't merge yet because of some unrelated audio issues in that PR: https://github.com/RickCarlino/KoalaSRS/pull/55
